server:
  port: 9090

spring:
  application:
    name:
      transfer-daemon

info:
  version: 0.0.1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/