server:
  port: 9099

spring:
  application:
    name:
      swagger-service

info:
  version: 0.0.1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/