server:
  port: 9099

spring:
  application:
    name:
      wallet-service

info:
  version: 0.0.1

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: /swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

wallet:
  service:
    logMessage: default was called