server:
  port: ${PORT:7070}

info:
  version: 1.3.3

spring:
  application:
    name:
      spring-admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/